### ISSUE TITLE
babel fails to transpile src/__tests__/Actions-test.js

### ISSUE THREAD

**Issue by chicoxyzzy** [acdlite/flummox#138]
```
/Users/Chico/Projects/flummox/node_modules/babel/lib/babel/helpers/parse.js:60
    throw err;
          ^
SyntaxError: src/__tests__/Actions-test.js: Unexpected token (89:62)
  87 |     });
  88 |
> 89 |     it('send async return value to Flux#dispatchAsync', async function() {
     |                                                               ^
  90 |       const actions = new TestActions();
  91 |       const actionId = actions.getActionIds().asyncAction;
  92 |       const dispatch = sinon.stub().returns(Promise.resolve());
    at raise (/Users/Chico/Projects/flummox/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:343:15)
    at unexpected (/Users/Chico/Projects/flummox/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2278:5)
    at expect (/Users/Chico/Projects/flummox/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2266:18)
    at parseExprList (/Users/Chico/Projects/flummox/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3740:9)
    at parseSubscripts (/Users/Chico/Projects/flummox/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3154:24)
    at parseExprSubscripts (/Users/Chico/Projects/flummox/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3119:12)
    at parseMaybeUnary (/Users/Chico/Projects/flummox/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3099:16)
    at parseExprOps (/Users/Chico/Projects/flummox/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3053:16)
    at parseMaybeConditional (/Users/Chico/Projects/flummox/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3029:16)
    at parseMaybeAssign (/Users/Chico/Projects/flummox/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3008:16)
make: *** [fast-js] Error 1
npm ERR! Test failed.  See above for more details.
```

**Comment by chicoxyzzy** [comment]
oh sorry updating babel fixes that
